import Link from "next/link";
import AppContextProvider from "app/AppContext";
import { Poppins, Kanit } from 'next/font/google';
import "./global.scss";

export const metadata = {
    title: 'EVE Capitalist',
    description: 'Generated by create next app',
    icons: {
        icon: "/eve-capitalist.png"
    }
}

interface LayoutProps {
    children: React.ReactNode
}

const poppins = Poppins({ weight: ['300', '400', '600', '800'], subsets: ['latin'] });
const kanit = Kanit({ weight: '400', subsets: ['latin'] })

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
                />
            </head>
            <body style={poppins.style} className="dark:bg-slate-900">
                <AppContextProvider>
                    <div className="sticky top-0 h-16 bg-black shadow-lg">
                        <div className="container flex flex-row items-center space-x-8">
                            <Link href="/">
                                <h1 className="tracking-wider text-xl font-semibold text-white" style={kanit.style}>EVE Capitalist</h1>
                            </Link>
                            <div className="flex flex-row space-x-4">
                                <Link href="/contracts" className="text-white hover:underline">
                                    Contracts
                                </Link>
                            </div>
                            <div className="flex flex-row space-x-4">
                                <Link href="/trade" className="text-white hover:underline">
                                    Trade
                                </Link>
                            </div>
                            <div className="flex-grow flex justify-end">
                                <button className="">
                                    <img src="https://everookies.com/wp-content/uploads/2021/04/image-22.png" className="w-full h-fit" />
                                </button>
                                <p className="hidden text-white">Hi, <u>Raduulle</u></p>
                            </div>
                        </div>
                    </div>
                    {children}
                </AppContextProvider>
            </body>
        </html>
    )
}
